:toc2:
:toc-title: API


= Resource: Operation

link:../../index.html[back <<] 


This resource represents a long-running operation that is the result of an API call.

.JSON representation
----
{
  "name": string,
  "metadata": {
    "@type": string,
    field1: ...,
    ...
  },
  "done": boolean,

  // Union field result can be only one of the following:
  "error": {
    object(Status)
  },
  "response": {
    "@type": string,
    field1: ...,
    ...
  }
  // End of list of possible types for union field result.
}
----

.Fields
[cols="1,1,5a"]
|===
|name	
|string
|The server-assigned name, which is only unique within the same service that originally returns it. If you use the default HTTP mapping, the name should have the format of operations/some/unique/name.

|metadata	
|object
|Service-specific metadata associated with the operation. It typically contains progress information and common metadata such as create time. Some services might not provide such metadata. Any method that returns a long-running operation should document the metadata type, if any.

An object containing fields of an arbitrary type. An additional field "@type" contains a URI identifying the type. Example: { "id": 1234, "@type": "types.example.com/standard/id" }.

|done	
|boolean
|If the value is false, it means the operation is still in progress. If true, the operation is completed, and either error or response is available.

Union field result. The operation result, which can be either an error or a valid response. If done == false, neither error nor response is set. If done == true, exactly one of error or response is set. result can be only one of the following:

|error	
|object(Status)
|The error result of the operation in case of failure or cancellation.

|response	
|object
|The normal response of the operation in case of success. If the original method returns no data on success, such as Delete, the response is google.protobuf.Empty. If the original method is standard Get/Create/Update, the response should be the resource. For other methods, the response should have the type XxxResponse, where Xxx is the original method name. For example, if the original method name is TakeSnapshot(), the inferred response type is TakeSnapshotResponse.

An object containing fields of an arbitrary type. An additional field "@type" contains a URI identifying the type. Example: { "id": 1234, "@type": "types.example.com/standard/id" }.
|===

== Status
The Status type defines a logical error model that is suitable for different programming environments, including REST APIs and RPC APIs. It is used by gRPC. The error model is designed to be:

* Simple to use and understand for most users
* Flexible enough to meet unexpected needs

=== Overview
The Status message contains three pieces of data: error code, error message, and error details. The error code should be an enum value of google.rpc.Code, but it may accept additional error codes if needed. The error message should be a developer-facing English message that helps developers understand and resolve the error. If a localized user-facing error message is needed, put the localized message in the error details or localize it in the client. The optional error details may contain arbitrary information about the error. There is a predefined set of error detail types in the package google.rpc that can be used for common error conditions.

=== Language mapping
The Status message is the logical representation of the error model, but it is not necessarily the actual wire format. When the Status message is exposed in different client libraries and different wire protocols, it can be mapped differently. For example, it will likely be mapped to some exceptions in Java, but more likely mapped to some error codes in C.

=== Other uses
The error model and the Status message can be used in a variety of environments, either with or without APIs, to provide a consistent developer experience across different environments.

Example uses of this error model include:

* Partial errors. If a service needs to return partial errors to the client, it may embed the Status in the normal response to indicate the partial errors.

* Workflow errors. A typical workflow has multiple steps. Each step may have a Status message for error reporting.

* Batch operations. If a client uses batch request and batch response, the Status message should be used directly inside batch response, one for each error sub-response.

* Asynchronous operations. If an API call embeds asynchronous operation results in its response, the status of those operations should be represented directly using the Status message.

* Logging. If some API errors are stored in logs, the message Status could be used directly after any stripping needed for security/privacy reasons.

.JSON representation
----
{
  "code": number,
  "message": string,
  "details": [
    {
      "@type": string,
      field1: ...,
      ...
    }
  ]
}
----


.Fields
[cols="1,1,5a"]
|===
|code	
|number
|The status code, which should be an enum value of google.rpc.Code.

|message	
|string
|A developer-facing error message, which should be in English. Any user-facing error message should be localized and sent in the google.rpc.Status.details field, or localized by the client.

|details[]	
|object
|A list of messages that carry the error details. There is a common set of message types for APIs to use.

An object containing fields of an arbitrary type. An additional field "@type" contains a URI identifying the type. Example: { "id": 1234, "@type": "types.example.com/standard/id" }.
|===

=== Methods

[cols="1,4"]
|===
|cancel
|Starts asynchronous cancellation on a long-running operation.
|delete
|Deletes a long-running operation.
|get
|Gets the latest state of a long-running operation.
|list
|Lists operations that match the specified filter in the request.
|===





== Method: v1.operations.cancel
Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns google.rpc.Code.UNIMPLEMENTED. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it becomes an operation with an Operation.error value with a google.rpc.Status.code of 1, corresponding to Code.CANCELLED.

=== HTTP request
`POST https://{site}/v1/operations/{name=operation/*}:cancel`

The URL uses Google API HTTP annotation syntax.

=== Path parameters
[cols="1,1,5a"]
|===
|name	
|string
|The name of the operation resource to be cancelled.
|===

=== Request body
The request body must be empty.

=== Response body
If successful, the response body will be empty.






== Method: v1.operations.delete
Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support this method, it returns google.rpc.Code.UNIMPLEMENTED.

=== HTTP request
`DELETE https://{site}/v1/operations/{name=operation/*}`

The URL uses Google API HTTP annotation syntax.

=== Path parameters
[cols="1,1,5a"]
|===
|name	
|string
|The name of the operation resource to be deleted.
|===

=== Request body
The request body must be empty.

=== Response body
If successful, the response body will be empty.





== Method: v1.operations.get
Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.

=== HTTP request
`GET https://{site}/v1/operations/{name=operation/*}`

The URL uses Google API HTTP annotation syntax.

=== Path parameters
[cols="1,1,5a"]
|===
|name	
|string
|The name of the operation resource.
|===

=== Request body
The request body must be empty.

=== Response body
If successful, the response body contains an instance of Operation.




== Method: v1.operations.list
Lists operations that match the specified filter in the request. 
If the server doesn't support this method, it returns UNIMPLEMENTED.

NOTE: the name binding allows API services to override the binding to use different resource name schemes,
 such as users/*/operations. 
 To override the binding, API services can add a binding such as `"/v1/{name=users/*}/operations"`
  to their service configuration. For backwards compatibility, the default name includes the operations collection id, 
  however overriding users must ensure the name binding is the parent resource, without the operations collection id.

=== HTTP request
`GET https://{site}/v1/operations`

The URL uses Google API HTTP annotation syntax.

=== Path parameters
[cols="1,1,5a"]
|===
|name	
|string
|The name of the operation's parent resource.
|===

=== Query parameters
[cols="1,1,5a"]
|===
|filter	
|string
|The standard list filter.

|pageSize	
|number
|The standard list page size.

|pageToken	
|string
|The standard list page token.
|===

=== Request body
The request body must be empty.

=== Response body
If successful, the response body contains data with the following structure:

The response message for Operations.ListOperations.

.JSON representation
----
{
  "operations": [
    {
      object(Operation)
    }
  ],
  "nextPageToken": string
}
----

.Fields
[cols="1,1,5a"]
|===
|operations[]	
|object(Operation)
|A list of operations that matches the specified filter in the request.

|nextPageToken	
|string
|The standard List next-page token.
|===
