:toc2:
:toc-title: API


= REST Resource: v1.datasets

link:../../index.html[back <<] 


== Resource: Dataset

Represents a dataset

A model can have multiple versions, each of which is a deployed, trained model ready to receive prediction requests.
 The model itself is just a container.

JSON representation
{
  "name": string,
  "description": string,
  "defaultVersion": {
    object(Version)
  },
  "regions": [
    string
  ],
  "onlinePredictionLogging": boolean
}
Fields
name	
string

Required. The name specified for the model when it was created.

The model name must be unique within the project it is created in.

description	
string

Optional. The description specified for the model when it was created.

defaultVersion	
object(Version)

Output only. The default version of the model. This version will be used to handle prediction requests that do not specify a version.

You can change the default version by calling projects.methods.versions.setDefault.

regions[]	
string

Optional. The list of regions where the model is going to be deployed. Currently only one region per model is supported. Defaults to 'us-central1' if nothing is set. See the available regions for ML Engine services. Note: * No matter where a model is deployed, it can always be accessed by users from anywhere, both for online and batch prediction. * The region for a batch prediction job is set by the region field when submitting the batch prediction job and does not take its value from this field.

onlinePredictionLogging	
boolean

Optional. If true, enables StackDriver Logging for online prediction. Default is false.

Methods
create
Creates a model which will later contain one or more versions.
delete
Deletes a model.
get
Gets information about a model, including its name, the description (if set), and the default version (if at least one version of the model has been deployed).
getIamPolicy
Gets the access control policy for a resource.
list
Lists the models in a project.
patch
Updates a specific model resource.
setIamPolicy
Sets the access control policy on the specified resource.
testIamPermissions
Returns permissions that a caller has on the specified resource.



== Methods
[cols="1,1,2,5a"]
|===
|list |GET | v1/datasets/ | Returns list ov datasets
|list |GET | v1/datasets/{name=dataset/*) | Returns specific dataset
|spec |GET | v1/datasets/{name=dataset/*}:spec | Returns dataset specification
|slice |POST | v1/datasets/{name=dataset/*}:slice | slice data set into temporary slices    
|===



== Method: v1.datasets.list

List all datasets.

=== HTTP request +
`GET https://{site}/v1/datasets`

The URL uses link:https://github.com/googleapis/googleapis/blob/master/google/api/http.proto?[Google API HTTP annotation] syntax.



=== Path parameters

[cols="1,1,5a"]
|===
| parent | string
|Required. The name of the project for which available locations are to be listed (since some locations might be whitelisted for specific projects).
|===

=== Query parameters
[cols="1,1,5a"]
|===
| pageToken	 |string| Optional. A page token to request the next page of results.

You get the token from the nextPageToken field of the response from the previous call.

|pageSize| number |
Optional. The number of locations to retrieve per "page" of results. If there are more remaining results than this number, the response message will contain a valid value in the nextPageToken field.

The default value is 20, and the maximum page size is 100.
|===

=== Request body
The request body must be empty.

=== Response body
If successful, the response body contains data with the following structure:

.JSON representation
----
{
  "locations": [
    {
      object(Location)
    }
  ],
  "nextPageToken": string
}
----

=== Fields

[cols="1,1,5a"]
|===
|locations[]	
|object(Location)|

Locations where at least one type of CMLE capability is available.
|nextPageToken	
|string
|
Optional. Pass this token as the pageToken field of the request for a subsequent call.
|===


== Method: v1.data.spec

Get the service account information associated with your project. You need this information in order to grant the service account permissions for the Google Cloud Storage location where you put your model training code for training the model with Google Cloud Machine Learning.

HTTP request
GET https://ml.googleapis.com/v1/{name=projects/*}:getConfig

The URL uses Google API HTTP annotation syntax.

Path parameters
Parameters
name	
string

Required. The project name.

Authorization requires the following Google IAM permission on the specified resource name:

ml.projects.getConfig
Request body
The request body must be empty.

Response body
If successful, the response body contains data with the following structure:

Returns service account information associated with a project.

JSON representation
{
  "serviceAccount": string,
  "serviceAccountProject": string,
  "config": {
    object(Config)
  }
}
Fields
serviceAccount	
string

The service account Cloud ML uses to access resources in the project.

serviceAccountProject	
string (int64 format)

The project number for serviceAccount.

config	
object(Config)

Authorization Scopes
Requires the following OAuth scope:

https://www.googleapis.com/auth/cloud-platform
For more information, see the Auth Guide.

Config
JSON representation
{
  "tpuServiceAccount": string
}
Fields
tpuServiceAccount	
string

The service account Cloud ML uses to run on TPU node.




== Method v1.data.slice

Returns data specification

.Example JSON:

[source,json]
----
   {
        slices: [0.8, 0.1, 0.1],
        names: [train, test, valid],
        type: random,
        random : 888666888L
    }
----
