:toc2:
:toc-title: API


= REST Resource: v1.datasets

link:../../index.html[back <<] 


== Resource: Dataset
Represents a dataset.

A dataset can have multiple versions/increases, usually with time.

.JSON representation
----
{
  "name": string,
  "description": string,
  "defaultVersion": {
    object(Version)
  },
  "isTimeSerie": boolean
}
----

=== Fields
[cols="1,1,5a"]
|===
|name	
|string
|Required. The name specified for the dataset when it was created. +
The dataset name must be unique.
|description	
|string
|Optional. The description specified for the dataset when it was created.
|defaultVersion	
|object(Version)
| Output only. The default version of the data. 
This version will be used to handle prediction requests that do not specify a version. +
You can change the default version by calling v1.datasets.updateData.
|isTimeSerie	
|boolean
| Optional. If true, it specifies data is time serie type. Default is false.
|===


=== Methods
[cols="1,5a"]
|===
|create
|Creates a new dataset.
|delete
|Deletes a dataset.
|get
|Gets information about a dataset, including its name, the description (if set), 
and the default version specification.
|list
|Lists the datasets in a project.
|patch
|Updates a specific model resource.
|===






== Method: v1.datasets.create
Creates a dataset.

=== HTTP request
`POST https://{site}/datasets`

The URL uses Google API HTTP annotation syntax.

=== Path parameters
None 

=== Request body
The request body contains an dataset body.

=== Response body
If successful, the response body contains a newly created instance of Dataset.



== Method: v1.datasets.delete
Deletes a dataset.


=== HTTP request
`DELETE https://{site}/v1/datasets/{name=dataset/*}`

The URL uses Google API HTTP annotation syntax.

=== Path parameters
[cols="1,1,5a"]
|===
|name	
|string
|Required. The name of the dataset.
|===

=== Request body
The request body must be empty.

=== Response body
If successful, the response body contains an instance of Operation.






== Method: v1.datasets.get
Gets information about a dataset, including its name, the description (if set),
 list of the versions/increases.

=== HTTP request
`GET https://{site|}/v1/datasets/{name=dataset/*}`

The URL uses Google API HTTP annotation syntax.

=== Path parameters
[cols="1,1,5a"]
|===
|name	
|string
|Required. The name of the dataset.
|===

=== Request body
The request body must be empty.

=== Response body
If successful, the response body contains an instance of Dataset.








== Method: v1.datasets.list
Lists the datasets in a project.

If there are no datasets that match the request parameters, the list request returns an empty response body: {}.

=== HTTP request
`GET https://{site}/v1/datasets`

The URL uses Google API HTTP annotation syntax.

=== Path parameters
None

=== Query parameters
[cols="1,1,5a"]
|===
|filter	
|string
|Optional. Specifies the subset of datasets to retrieve.

|pageToken	
|string
|Optional. A page token to request the next page of results. +
You get the token from the nextPageToken field of the response from the previous call.
|pageSize	
|number
|Optional. The number of datasets to retrieve per "page" of results. 
If there are more remaining results than this number, the response message will contain a valid value 
in the nextPageToken field. +
The default value is 20, and the maximum page size is 100.
|===

=== Request body
The request body must be empty.

=== Response body
If successful, the response body contains data with the following structure:

Response message for the datasets.list method.

.JSON representation
----
{
  "datasets": [
    {
      object(Dataset)
    }
  ],
  "nextPageToken": string
}
----

.Fields
[cols="1,1,5a"]
|===
|models[]	
|object(Dataset)
|The list of datasets.

|nextPageToken	
|string
|Optional. Pass this token as the pageToken field of the request for a subsequent call.
|===




== Method: v1.datasets.patch
Updates a specific dataset with increased data.


=== HTTP request
`PATCH https://{site}/v1/datasets/{name=dataset/*}`

The URL uses Google API HTTP annotation syntax.

=== Path parameters

[cols="1,1,5a"]
|===
|name
|string
|name of the dataset to be increased
|===


=== Query parameters
[cols="1,1,5a"]
|===
|update	
|string 
|Required. Specifies the new branch of data. +
 
For example, if data is time serie type new branch could be new 1 week of data between 01/06/2018 and 08/06/2018:
`+{ "description": "1 week od data between...", "defaultVersion": { "name":"version_1" } }+`

A comma-separated list of fully qualified names of fields. Example: "user.displayName,photo".
|===

=== Request body
The request body contains an instance of Dataset.

=== Response body
If successful, the response body contains an instance of Operation.







