:toc2:
:toc-title: API




= REST Resource: v1.ads

link:../../index.html[back <<] 


== Resource: DataScientistFlow

Represents DataScientistFlow job, metamodel and actions on them.

.JSON representation
----
{
  "jobId": string,
  "createTime": string,
  "startTime": string,
  "endTime": string,
  "state": enum(State),
  "errorMessage": string,

  "trainingInput": {
    object(TrainingInput)
  },

  "trainingOutput": {
    object(TrainingOutput)
  }
}
----

.Fields
[cols="1,1,5a"]
|===
|jobId	
|string
|Required. The user-specified id of the job.

|createTime	
|string (Timestamp format)
|Output only. When the job was created.

A timestamp in RFC3339 UTC "Zulu" format, accurate to nanoseconds. Example: "2014-10-02T15:01:23.045123456Z".

|startTime	
|string (Timestamp format)
|Output only. When the job processing was started.

A timestamp in RFC3339 UTC "Zulu" format, accurate to nanoseconds. Example: "2014-10-02T15:01:23.045123456Z".

|endTime	
|string (Timestamp format)
|Output only. When the job processing was completed.

A timestamp in RFC3339 UTC "Zulu" format, accurate to nanoseconds. Example: "2014-10-02T15:01:23.045123456Z".

|state	
|enum(State)
|Output only. The detailed state of a job.

|errorMessage	
|string
|Output only. The details of a failure or a cancellation.

|trainingInput
|object(TrainingInput)
|Input parameters to create a training job.

|trainingOutput	
|object(TrainingOutput)
|The current training job result.

|===

=== TrainingInput
Represents input parameters for a training job.
 

.JSON representation
----
{
  "scaleTier": enum(ScaleTier),
  "masterType": string,
  "workerType": string,
  "parameterServerType": string,
  "workerCount": string,
  "parameterServerCount": string,
  "packageUris": [
    string
  ],
  "pythonModule": string,
  "args": [
    string
  ],
  "hyperparameters": {
    object(HyperparameterSpec)
  },
  "jobDir": string,
  "runtimeVersion": string,
  "pythonVersion": string
}
----


.Fields
[cols="1,1,5a"]
|===
|scaleTier	
|enum(ScaleTier)
|Required. Specifies the machine types, the number of replicas for workers 
and parameter servers.

|masterType	
|string
|Optional. Specifies the type of virtual machine to use for your training job's master worker.

The following types are supported:

* standard
A basic machine configuration suitable for training simple models with small to moderate datasets.
* large_model
A machine with a lot of memory, specially suited for parameter servers when your model is large (having many hidden layers or layers with very large numbers of nodes).
* complex_model_s
A machine suitable for the master and workers of the cluster when your model requires more computation than the standard machine can handle satisfactorily.
* complex_model_m
A machine with roughly twice the number of cores and roughly double the memory of complex_model_s.
* complex_model_l
A machine with roughly twice the number of cores and roughly double the memory of complex_model_m.
* standard_gpu
A machine equivalent to standard that also includes a single NVIDIA Tesla K80 GPU. See more about using GPUs to train your model.
* complex_model_m_gpu
A machine equivalent to complex_model_m that also includes four NVIDIA Tesla K80 GPUs.
* complex_model_l_gpu
A machine equivalent to complex_model_l that also includes eight NVIDIA Tesla K80 GPUs.
* standard_p100
A machine equivalent to standard that also includes a single NVIDIA Tesla P100 GPU. The availability of these GPUs is in the Beta launch stage.
* complex_model_m_p100
A machine equivalent to complex_model_m that also includes four NVIDIA Tesla P100 GPUs. The availability of these GPUs is in the Beta launch stage.
* cloud_tpu
A TPU VM including one Cloud TPU. The availability of Cloud TPU is in Beta launch stage. See more about using TPUs to train your model.
You must set this value when scaleTier is set to CUSTOM.

|workerType	
|string
|Optional. Specifies the type of virtual machine to use for your training job's worker nodes.

The supported values are the same as those described in the entry for masterType.

This value must be present when scaleTier is set to CUSTOM and workerCount is greater than zero.

|parameterServerType	
|string
|Optional. Specifies the type of virtual machine to use for your training job's parameter server.

The supported values are the same as those described in the entry for masterType.

This value must be present when scaleTier is set to CUSTOM and parameterServerCount is greater than zero.

|workerCount	
|string (int64 format)
|Optional. The number of worker replicas to use for the training job. Each replica in the cluster will be of the type specified in workerType.

This value can only be used when scaleTier is set to CUSTOM. If you set this value, you must also set workerType.

|parameterServerCount	
|string (int64 format)
|Optional. The number of parameter server replicas to use for the training job. Each replica in the cluster will be of the type specified in parameterServerType.

This value can only be used when scaleTier is set to CUSTOM.If you set this value, you must also set parameterServerType.

|packageUris[]	
|string
|Required. The  Storage location of the packages with the training program and any additional dependencies. The maximum number of package URIs is 100.

|hyperparameters	
|object(HyperparameterSpec)
|Optional. The set of Hyperparameters to tune.


|jobDir	
|string
|Optional. A Google Cloud Storage path in which to store training outputs and other data needed for training. This path is passed to your TensorFlow program as the '--job-dir' command-line argument. The benefit of specifying this field is that Cloud ML validates the path for use in training.

|runtimeVersion	
|string
|Optional. The Google Cloud ML runtime version to use for training. If not set, Google Cloud ML will choose a stable version, which is defined in the documentation of runtime version list.
|===

=== ScaleTier
A scale tier is an abstract representation of the resources  ML will allocate to a training job. When selecting a scale tier for your training job, you should consider the size of your training dataset and the complexity of your model. As the tiers increase, virtual machines are added to handle your job, and the individual machines in the cluster generally have more memory and greater processing power than they do at lower tiers. The number of training units charged per hour of processing increases as tiers get more advanced. Refer to the pricing guide for more details. Note that in addition to incurring costs, your use of training resources is constrained by the quota policy.

.Enums
[cols="1,4"]
|===
|BASIC	|A single worker instance. This tier is suitable for learning how to use Cloud ML, and for experimenting with new models using small datasets.
|STANDARD_1	|Many workers and a few parameter servers.
|PREMIUM_1	|A large number of workers with many parameter servers.
|BASIC_GPU	|A single worker instance with a GPU.
|BASIC_TPU	|A single worker instance with a Cloud TPU. The availability of Cloud TPU is in Beta launch stage.
|CUSTOM	
|The CUSTOM tier is not a set tier, but rather enables you to use your own cluster specification. When you use this tier, set values to configure your processing cluster according to these guidelines:

* You must set TrainingInput.masterType to specify the type of machine to use for your master node. This is the only required setting.

* You may set TrainingInput.workerCount to specify the number of workers to use. If you specify one or more workers, you must also set TrainingInput.workerType to specify the type of machine to use for your worker nodes.

* You may set TrainingInput.parameterServerCount to specify the number of parameter servers to use. If you specify one or more parameter servers, you must also set TrainingInput.parameterServerType to specify the type of machine to use for your parameter servers.

Note that all of your workers must use the same machine type, which can be different from your parameter server type and master type. Your parameter servers must likewise use the same machine type, which can be different from your worker type and master type.
|===

== HyperparameterSpec
Represents a set of hyperparameters to optimize.

.JSON representation
----
{
  "goal": enum(GoalType),
  "params": [
    {
      object(ParameterSpec)
    }
  ],
  "maxTrials": number,
  "maxParallelTrials": number,
  "hyperparameterMetricTag": string,
  "resumePreviousJobId": string,
  "enableTrialEarlyStopping": boolean,
  "algorithm": enum(Algorithm)
}
----

.Fields
[cols="1,1,5a"]
|===
|goal	
|enum(GoalType)
|Required. The type of goal to use for tuning. Available types are MAXIMIZE and MINIMIZE.

Defaults to MAXIMIZE.

|params[]	
|object(ParameterSpec)
|Required. The set of parameters to tune.

|maxTrials	
|number
|Optional. How many training trials should be attempted to optimize the specified hyperparameters.

Defaults to one.

|maxParallelTrials	
|number

|Optional. The number of training trials to run concurrently. You can reduce the time it takes to perform hyperparameter tuning by adding trials in parallel. However, each trail only benefits from the information gained in completed trials. That means that a trial does not get access to the results of trials running at the same time, which could reduce the quality of the overall optimization.

Each trial will use the same scale tier and machine types.

Defaults to one.

|hyperparameterMetricTag	
|string
|Optional. The  summary tag name to use for optimizing trials. 
  By default, "training/hptuning/metric" will be used.

|resumePreviousJobId	
|string
|Optional. The prior hyperparameter tuning job id that users hope to continue with. The job id will be used to find the corresponding vizier study guid and resume the study.

|enableTrialEarlyStopping	
|boolean
|Optional. Indicates if the hyperparameter tuning job enables auto trial early stopping.

|algorithm	
|enum(Algorithm)
|Optional. The search algorithm specified for the hyperparameter tuning job. Uses the default CloudML Engine hyperparameter tuning algorithm if unspecified.
|===

=== GoalType
The available types of optimization goals.

.Enums
[cols="1,4"]
|===
|UNSPECIFIED	|Goal Type will default to maximize.
|MAXIMIZE	|Maximize the goal metric.
|MINIMIZE	|Minimize the goal metric.
|===

=== ParameterSpec
Represents a single hyperparameter to optimize.

.JSON representation
----
{
  "parameterName": string,
  "type": enum(ParameterType),
  "minValue": number,
  "maxValue": number,
  "categoricalValues": [
    string
  ],
  "discreteValues": [
    number
  ],
  "scaleType": enum(ScaleType)
}
----
.Fields
[cols="1,1,5a"]
|===
|parameterName	
|string
|Required. The parameter name must be unique amongst all ParameterConfigs in a HyperparameterSpec message. E.g., "learning_rate".

|type	
|enum(ParameterType)
|Required. The type of the parameter.

|minValue	
|number
|Required if type is DOUBLE or INTEGER. This field should be unset if type is CATEGORICAL. This value should be integers if type is INTEGER.

|maxValue	
|number
|Required if type is DOUBLE or INTEGER. This field should be unset if type is CATEGORICAL. This value should be integers if type is INTEGER.

|categoricalValues[]	
|string
|Required if type is CATEGORICAL. The list of possible categories.

|discreteValues[]	
|number
|Required if type is DISCRETE. A list of feasible points. The list should be in strictly increasing order. For instance, this parameter might have possible settings of 1.5, 2.5, and 4.0. This list should not contain more than 1,000 values.

|scaleType	
|enum(ScaleType)
|Optional. How the parameter should be scaled to the hypercube. Leave unset for categorical parameters. Some kind of scaling is strongly recommended for real or integral parameters (e.g., UNIT_LINEAR_SCALE).
|===

=== ParameterType
The type of the parameter.

.Enums
[cols="1,4"]
|===
|UNSPECIFIED	|You must specify a valid type. Using this unspecified type will result in an error.
|DOUBLE	|Type for real-valued parameters.
|INTEGER	|Type for integral parameters.
|CATEGORICAL	|The parameter is categorical, with a value chosen from the categories field.
|DISCRETE	|The parameter is real valued, with a fixed set of feasible points. If type==DISCRETE, feasible_points must be provided, and {minValue, maxValue} will be ignored.
|===

=== ScaleType
The type of scaling that should be applied to this parameter.

.Enums
[cols="1,4"]
|===
|NONE	|By default, no scaling is applied.
|UNIT_LINEAR_SCALE	|Scales the feasible space to (0, 1) linearly.
|UNIT_LOG_SCALE	|Scales the feasible space logarithmically to (0, 1). The entire feasible space must be strictly positive.
|UNIT_REVERSE_LOG_SCALE	|Scales the feasible space "reverse" logarithmically to (0, 1). The result is that values close to the top of the feasible space are spread out more than points near the bottom. The entire feasible space must be strictly positive.
|===

=== Algorithm
The available search algorithms of hyperparameter tuning.

.Enums
[cols="1,4"]
|===
|UNSPECIFIED	|The default algorithm used by hyperparameter tuning service.
|GENETIC	| Genetic algorithm 
|GRID_SEARCH	|Simple grid search within the feasible space. To use grid search, all parameters must be INTEGER, CATEGORICAL, or DISCRETE.
|RANDOM_SEARCH	|Simple random search within the feasible space.
|===


== TrainingOutput
Represents results of a training job. Output only.

.JSON representation
----
{
  "completedTrialCount": string,
  "trials": [
    {
      object(HyperparameterOutput)
    }
  ],
  "consumedMLUnits": number,
  "isHyperparameterTuningJob": boolean
}
----


.Fields
[cols="1,1,5a"]
|===
|completedTrialCount	
|string (int64 format)
|The number of hyperparameter tuning trials that completed successfully. Only set for hyperparameter tuning jobs.

|trials[]	
|object(HyperparameterOutput)
|Results for individual Hyperparameter trials. Only set for hyperparameter tuning jobs.

|consumedMLUnits	
|number
|The amount of ML units consumed by the job.

|isHyperparameterTuningJob	
|boolean
|Whether this job is a hyperparameter tuning job.
|===

== HyperparameterOutput
Represents the result of a single hyperparameter tuning trial from a training job. The TrainingOutput object that is returned on successful completion of a training job with hyperparameter tuning includes a list of HyperparameterOutput objects, one for each successful trial.

.JSON representation
----
{
  "trialId": string,
  "hyperparameters": {
    string: string,
    ...
  },
  "finalMetric": {
    object(HyperparameterMetric)
  },
  "isTrialStoppedEarly": boolean,
  "allMetrics": [
    {
      object(HyperparameterMetric)
    }
  ]
}
----


.Fields
[cols="1,1,5a"]
|===
|trialId	
|string
|The trial id for these results.

|hyperparameters	
|map (key: string, value: string)
|The hyperparameters given to this trial.

An object containing a list of "key": value pairs. Example: { "name": "wrench", "mass": "1.3kg", "count": "3" }.

|finalMetric	
|object(HyperparameterMetric)
|The final objective metric seen for this trial.

|isTrialStoppedEarly	
|boolean
|True if the trial is stopped early.

|allMetrics[]	
|object(HyperparameterMetric)
|All recorded object metrics for this trial. This field is not currently populated.
|===

=== HyperparameterMetric
An observed value of a metric.

.JSON representation
----
{
  "trainingStep": string,
  "objectiveValue": number
}
----

.Fields
[cols="1,1,5a"]
|===
|trainingStep	
|string (int64 format)
|
The global training step for this metric.

|objectiveValue	
|number
|
The objective value at this training step.
|===







==== Methods
[cols="1,1,2,5a"]
|===
|cancel
|POST |/v1/ads/{name=job/*}:cancel
|Cancels a running ADS training job.
|create
|POST |/v1/ads/jobs
|Creates a training ads job.
|get
|GET |/v1/ads/{name=jobs/*}
|Describes a ads job.
|list
|GET |/v1/ads/jobs
|Lists the adsd jobs in the project.
|===















== Method: v1.ads.cancel
Cancels a running ADS training job.

HTTP request
POST https://{site}/v1/ads/{name=job/*}:cancel

The URL uses Google API HTTP annotation syntax.

=== Path parameters
Parameters
[cols="1,1,5a"]
|===
|name	
|string
|Required. The name of the job to cancel.
|===

=== Request body
The request body must be empty.

=== Response body
If successful, the response body will be empty.







== Method: v1.ads.create
Creates a new training job.

=== HTTP request
POST https://{site}/v1/ads/jobs

The URL uses Google API HTTP annotation syntax.

Path parameters
Parameters
[cols="1,1,5a"]
|===
|parent	
|string
|Required. The project name.
|===

=== Request body
The request body contains an instance of Job.

=== Response body
If successful, the response body contains a newly created instance of Job.





== Method: v1.ads.get
Describes a job.

=== HTTP request
GET https://{site}/v1/ads/{name=jobs/*}

The URL uses Google API HTTP annotation syntax.

Path parameters
Parameters
[cols="1,1,5a"]
|===
|name	
|string
|Required. The name of the job to get the description of.
|===

=== Request body
The request body must be empty.

=== Response body
If successful, the response body contains an instance of Job.










== Method: v1.ads.list
Lists the jobs in the project.

If there are no jobs that match the request parameters, the list request returns an empty response body: {}.

=== HTTP request
GET https://{site}/v1/ads/jobs

The URL uses Google API HTTP annotation syntax.

=== Path parameters
Parameters
[cols="1,1,5a"]
|===
|parent	
|string
|Required. The name of the project for which to list jobs.
|===

=== Query parameters
Parameters
[cols="1,1,5a"]
|===
|filter	
|string
|Optional. Specifies the subset of jobs to retrieve. 

|pageToken	
|string
|Optional. A page token to request the next page of results.

You get the token from the nextPageToken field of the response from the previous call.

|pageSize	
|number
|Optional. The number of jobs to retrieve per "page" of results. If there are more remaining results than this number, the response message will contain a valid value in the nextPageToken field.

The default value is 20, and the maximum page size is 100.
|===

=== Request body
The request body must be empty.

=== Response body
If successful, the response body contains data with the following structure:

Response message for the jobs.list method.

.JSON representation
----
{
  "ads": [
    {
      object(DataScientistFlow)
    }
  ],
  "nextPageToken": string
}
----

.Fields

[cols="1,1,5a"]
|===
|ads[]	
|object(DataScientistFlow)
|The list of DataScientistFlow jobs.

|nextPageToken	
|string

|Optional. Pass this token as the pageToken field of the request for a subsequent call.
|===
























