:toc2:
:toc-title: API

= ADS Flow

link:../index.html[back <<] 

The ADS methods performs transformations, trainings, model selection and model reasoning 
 on the data in the request.

This page describes the format of the ADS Flow request body and of the response body,
 as well as the URL format of the HTTP request. 
 
While request body is almost optional - everything shoulld be automatic - response body is extremely important,
 it contains all methods: transformations, models, and found parameters for best data transformations and 
 model hyperparameters processing. 


== Request body

The request body contains data with the following structure:

.JSON representation
----
{
  "dataset": {
        "train": <train data url>,
        "test": <test data url>,
        "valid": <valid data url>,
  },
  
  "afe": {
        "levels": int,
        "allTransformations": boolean,
        "transformations": [
         <transformation type>,
         ... 
         ]
   },
  "algorithms": {
        "allAlgorithms": boolean,
        "algorithms": [
            <algorithm>|[<hyperparams>],
            ...
        ],
        "objective": <objective>,
       
   }.
   "interpretation": {  
      "lime": {
          "k": int,
          ...
       }
      "loco": {
            "process":boolean,
       }  
   }
}
----

The data object is required, and must contain the list of data sources to get model for, other are optional 
since they have default values and whole process should be as much automatic as possible.

=== Fields
[cols="1,1,5a"]
|===
| dataset | object | Required. Source of train, test, validation data to be processsed.
| afe | object |  Optional. Defines scope of automatic feature engineering:

- how many levels of futures processing

- list of transformations to be used

If not specified default values will be processed. See below.
|algorithms| object | Optional. List of ML algorithms to take part in race for best. 



If not specified default values will be processed. See below.
|lime | object | Parameters for lime automatic interpretation.
|loco | object | Parameters for LOCO - input data explanation (RCA).
|===

.AFE structure
[cols="1,1,5a"]
|===
|levels | int | Optional. How many levels of data transformation should be used.

Default value 3.
|allTransformations | boolean | Optional. Should use all provided transformations

Default true.

| nanTransformations | enum | Optional. How to process non existing values 
.footnote:[some algorithms could not get NANs as input - XGBoost/SDAR]

* NAN transformations 
** None  
** Zero 
** ConstValue 
** Mean 
** Median 
** LastGoodValue 
** DailyAverage 
** DailyAverageSoftened 

Default is None.

|transformations[] | list | Optional. List of transformations to be used in processing.

Currently supported:

* math
** log
** ln
** sqrt
** sqrt3
** power
** qube
** sin
** cos
** tan
** 10^x
** e^x
* time series
** Y - year
** M - month of year
** WoY - week of year
** WoM - week of month
** DoY - day of year
** D - day of month
** DoW - day of week
** HoY - hour of year
** HoM - hour of month
** HoW - hour of week
** H - hour of day
** MoM - minute of month
** MoW - minute of week
** MoD - minute of day
** M - minute of hour
** SoM - second of month
** SoW - second of week
** SoD - second of day
** SoH - second of hour
** S - second of minute
* distribution transformation
** BoxCox
** Partial Least Square
** Winsorization

|===


.Algorithm structure
[cols="1,1,5a"]
|===
|allAlgorithms | boolean | Optional. Should data be testes against all available algorithms.

Default value true.

|algorithms[] | list | Optional. List of algorithms to be used in processing.
Each algorithm can contain their own hyperparameters scope.

Currently supported:

* GLM [H2O]
* K-means [H2O]
* Boosting Treee [H2O]
* Random Forest [H2O]
* SDAR [Jaro]
* RNN [Tensorflow]
* XGBoost [XGBoost]

**Hyperparameters are depending on each of algorithm.** They are specified as list structure: +
`<parameter name>: [ <value 1>,<value 2>, ... ]`

|===


=== Examples
Below are some examples of request bodies.

@todo




== Response body
Responses are very important as they contains output of whole Automatic Data Scientist flow:
 - all columns
 - chosen transformations and they output - method used and they parameters (ie: found BoxCox scalling)
 - chosen models with they hyperparameters
 - output of model rationalization - lime/lcoc

If the call is successful, the response body contains description of whole ADS Flow:

.JSON representation
----
{
  "dataset": {
        "train": <train data url>,
        "test": <test data url>,
        "valid": <valid data url>,
  },
  
  "afe": {
        "levels":[
            {
                "level": <number of level>,
                "transformations": [
                    <column>,<new name>,<transformation with parameters>,
                ...
                ]
            },
            ...
         ]
   }
  "algorithms": {
        "allAlgorithms": boolean,
        "algorithms": [
            <algorithm>|[<hyperparams>],
            ...
        ],
        "objective": <objective>,
       
   }
   "interpretation": {  
      "lime": {
          "k": int,
          ...
       }
      "loco": {
            "process":boolean,
    
       }  
   }
}
----

If ADS fails for any instance, the response body contains no flow. 
Instead, it contains a single error entry:
----
{
  "error": string
}
----

On error, the error string contains a message describing the problem. 


=== Response body examples
The following examples show some possible responses:

@todo

A response when there is an error processing an input instance:
----
{"error": "Divide by zero"}
----

