:toc2:
:toc-title: Contents

= Policy

link:../index.html[back <<] 


Defines an Identity and Access Management (IAM) policy. 
It is used to specify access control policies for  resources.

A Policy consists of a list of bindings. 
A binding binds a list of members to a role, where the members can be user accounts, groups, domains, and service accounts.
A role is a named list of defined permissions.

.JSON Example
----
{
  "bindings": [
    {
      "role": "roles/owner",
      "members": [
        "user:user@example.com",
        "group:admins@example.com",
        "domain:site.com",
        "serviceAccount:my-other-app@site.com"
      ]
    },
    {
      "role": "roles/viewer",
      "members": ["user:sean@example.com"]
    }
  ]
}
----

.YAML Example
----
bindings:
- members:
  - user:mike@example.com
  - group:admins@example.com
  - domain:google.com
  - serviceAccount:my-other-app@site.com
  role: roles/owner
- members:
  - user:sean@example.com
  role: roles/viewer
----
  
For a description of IAM and its features, see the IAM developer's guide.

.JSON representation
----
{
  "version": number,
  "bindings": [
    {
      object(Binding)
    }
  ],
  "auditConfigs": [
    {
      object(AuditConfig)
    }
  ],
  "etag": string
}
----

.Fields
[cols="1,1,5a"]
|===
|bindings[]	
|object(Binding)
|Associates a list of members to a role. bindings with no members will result in an error.

|auditConfigs[]	
|object(AuditConfig)
|Specifies  audit logging configuration for this policy.

|etag	
|string (bytes format)
|etag is used for optimistic concurrency control as a way to help prevent simultaneous updates 
of a policy from overwriting each other. It is strongly suggested that systems make use of the etag 
in the read-modify-write cycle to perform policy updates in order to avoid race conditions: 
An etag is returned in the response to getIamPolicy, and systems are expected to put that etag in the request 
to setIamPolicy to ensure that their change will be applied to the same version of the policy.

If no etag is provided in the call to setIamPolicy, then the existing policy is overwritten blindly.

A base64-encoded string.
|===


== Binding
Associates members with a role.

.JSON representation
----
{
  "role": string,
  "members": [
    string
  ]
}
----

.Fields
[cols="1,1,5a"]
|===
|role	
|string
|Role that is assigned to members. For example, roles/viewer, roles/editor, or roles/owner. Required

|members[]	
|string
|Specifies the identities requesting access for a  resource. members can have the following values:

allUsers: A special identifier that represents anyone who is on the internet.

allAuthenticatedUsers: A special identifier that represents anyone who is authenticated with a service account.

user:{emailid}: An email address that represents a specific account.

serviceAccount:{emailid}: An email address that represents a service account. For example, my-other-app@site.com.

group:{emailid}: An email address that represents a Google group. For example, admins@example.com.

domain:{domain}: A Google Apps domain name that represents all the users of that domain. For example, site.com or example.com.
|===

== AuditConfig
Specifies the audit configuration for a service. 
The configuration determines which permission types are logged, and what identities, if any, are exempted from logging. 
An AuditConfig must have one or more AuditLogConfigs.

If there are AuditConfigs for both allServices and a specific service, the union of the two AuditConfigs is used 
for that service: the log_types specified in each AuditConfig are enabled, and the exemptedMembers in each 
AuditLogConfig are exempted.

Example Policy with multiple AuditConfigs:
----
{
  "auditConfigs": [
    {
      "service": "allServices"
      "auditLogConfigs": [
        {
          "logType": "DATA_READ",
          "exemptedMembers": [
            "user:foo@mail.com"
          ]
        },
        {
          "logType": "DATA_WRITE",
        },
        {
          "logType": "ADMIN_READ",
        }
      ]
    },
    {
      "service": "fooservice.example.com"
      "auditLogConfigs": [
        {
          "logType": "DATA_READ",
        },
        {
          "logType": "DATA_WRITE",
          "exemptedMembers": [
            "user:bar@mail.com"
          ]
        }
      ]
    }
  ]
}
----

For fooservice, this policy enables DATA_READ, DATA_WRITE and ADMIN_READ logging. 
It also exempts foo@mail.com from DATA_READ logging, and bar@mail.com from DATA_WRITE logging.


.JSON representation
----
{
  "service": string,
  "auditLogConfigs": [
    {
      object(AuditLogConfig)
    }
  ]
}
----

.Fields
[cols="1,1,5a"]
|===
|service	
|string
|Specifies a service that will be enabled for audit logging. allServices is a special value that covers all services.

|auditLogConfigs[]	
|object(AuditLogConfig)
|The configuration for logging of each type of permission.
|===

== AuditLogConfig
Provides the configuration for logging a type of permissions. Example:
----
{
  "auditLogConfigs": [
    {
      "logType": "DATA_READ",
      "exemptedMembers": [
        "user:foo@gmail.com"
      ]
    },
    {
      "logType": "DATA_WRITE",
    }
  ]
}
----
This enables 'DATA_READ' and 'DATA_WRITE' logging, while exempting foo@gmail.com from DATA_READ logging.

.JSON representation
----
{
  "logType": enum(LogType),
  "exemptedMembers": [
    string
  ]
}
----

.Fields 

[cols="1,1,5a"]
|===
|logType	
|enum(LogType)
|The log type that this config enables.

|exemptedMembers[]	
|string
|Specifies the identities that do not cause logging for this type of permission. 
Follows the same format of Binding.members.
|===

== LogType
The list of valid permission types for which logging can be configured. 
Admin writes are always logged, and are not configurable.


."Enums"

[cols="1,3"]
|===
|LOG_TYPE_UNSPECIFIED	|Default case. Should never be this.
|ADMIN_READ	|Admin reads. Example: IAM getIamPolicy
|DATA_WRITE	|Data writes. Example: SQL Users create
|DATA_READ	|Data reads. Example: SQL Users list
|===